module.exports = [
  {
    id: 'home',
    label: 'Home',
    org: 'Borivali, Mumbai',
    role: 'Where it all began',
    dateRange: 'Origins',
    type: 'home',
    coordinates: [72.8573123399746, 19.229218251390936],
    location: 'Borivali, Mumbai, India',
    logo: null,
    skills: [],
    bullets: [
      'Grew up in the northern suburbs of Mumbai.',
      'The city of hustle, monsoons, and vada pav — where curiosity about computers first sparked.'
    ],
    photos: [],
    transitionType: null,
  },
  {
    id: 'spit',
    label: 'SPIT',
    org: 'Sardar Patel Institute of Technology',
    role: 'B.Tech in Computer Engineering',
    dateRange: 'Aug 2017 – May 2021',
    type: 'education',
    coordinates: [72.83611859144854, 19.123210075271743],
    location: 'Andheri, Mumbai, India',
    logo: '/assets/images/spit-logo.png',
    skills: ['Java', 'Python', 'Data Structures', 'DBMS', 'OS', 'Networks'],
    bullets: [
      'Graduated with a B.Tech in Computer Engineering.',
      'Built a strong foundation in systems, algorithms, and software design.',
    ],
    photos: [],
    transitionType: 'road',
  },
  {
    id: 'ltimindtree',
    label: 'LTIMindtree',
    org: 'LTIMindtree',
    role: 'Software Engineer',
    dateRange: 'Jan 2021 – Jun 2023',
    type: 'work',
    coordinates: [72.89190676588217, 19.157388652699623],
    location: 'Powai, Mumbai, India',
    logo: '/assets/images/ltimindtree-logo-blue.png',
    skills: ['Python', 'SQL', 'ETL', 'Azure', 'Spark', 'Data Pipelines'],
    bullets: [
      'Built and maintained large-scale data pipelines processing millions of records.',
      'Led migration of legacy ETL workflows to cloud-native Azure infrastructure.',
    ],
    photos: [],
    transitionType: 'road',
  },
  {
    id: 'tamu-ms',
    label: 'Texas A&M',
    org: 'Texas A&M University',
    role: 'MS in Management Information Systems',
    dateRange: 'Aug 2023 – May 2025',
    type: 'education',
    coordinates: [-96.3509327959807, 30.610918712268887],
    location: 'College Station, TX',
    logo: '/assets/images/tamu-logo.png',
    skills: ['Data Engineering', 'Machine Learning', 'Cloud Architecture', 'Analytics'],
    bullets: [
      'Pursued graduate studies at Texas A&M — a 14,000 km flight from home.',
      'Focused on data systems, AI applications, and the intersection of tech and management.',
      'Served as Teaching Assistant for database and analytics courses.',
    ],
    photos: [],
    transitionType: 'flight',
  },
  {
    id: 'tamu-intern',
    label: 'Internship',
    org: 'Texas A&M (Remote)',
    role: 'Data Engineer Intern',
    dateRange: 'Aug 2025 – Feb 2026',
    type: 'work',
    coordinates: [-121.9285478998405, 37.363915880380404],
    location: 'San Jose, CA (Remote)',
    logo: '/assets/images/tamu-logo.png',
    skills: ['Python', 'dbt', 'Snowflake', 'Airflow', 'SQL'],
    bullets: [
      'Remote internship based out of San Jose, California.',
      'Designed and deployed data transformation pipelines using dbt and Snowflake.',
    ],
    photos: [],
    transitionType: 'flight',
  },
  {
    id: 'hcltech',
    label: 'HCLTech',
    org: 'HCLTech',
    role: 'Software Engineer',
    dateRange: '2026 – Present',
    type: 'work',
    coordinates: [-122.14091255737284, 47.63891007775006],
    location: 'Redmond, WA',
    logo: '/assets/images/HCLT-logo.png',
    skills: ['Cloud', 'Data Engineering', 'Enterprise Systems'],
    bullets: [
      'Based in Redmond, Washington — the Pacific Northwest.',
      'Building large-scale enterprise data solutions.',
    ],
    photos: [],
    transitionType: 'flight',
  },
];
