module.exports = [
  // ── Experience stops (type: home / work / education) ─────────────────────
  {
    id: 'home',
    label: 'Home',
    org: 'Borivali, Mumbai',
    role: 'Where it all began',
    dateRange: 'Origins',
    type: 'home',
    coordinates: [72.8573123399746, 19.229218251390936],
    location: 'Borivali, Mumbai, India',
    logo: null,
    chapter: 'Chapter I: Roots',
    quote: 'Every journey starts with the street you grew up on.',
    skills: [],
    bullets: [
      'Grew up in the northern suburbs of Mumbai.',
      'The city of hustle, monsoons, and vada pav — where curiosity about tech first sparked.',
    ],
    story: 'I grew up in Mumbai — a city that has never stopped moving, and it quietly taught me that momentum is a mindset.\n\nThe curiosity about tech started here, while being curious and watching Discovery Channel, science documentaries, and time-travel shows a little too much.',
    photos: [
      // { src: '/assets/images/journey/home/childhood.jpg', caption: 'Borivali — the building and the street that started everything.' },
    ],
    transitionType: null,
  },
  {
    id: 'spit',
    label: 'SPIT',
    org: 'Sardar Patel Institute of Technology',
    role: 'B.Tech in Electronics & Telecommunication Engineering',
    dateRange: 'Aug 2017 – May 2021',
    type: 'education',
    coordinates: [72.83611859144854, 19.123210075271743],
    location: 'Andheri, Mumbai, India',
    logo: '/assets/images/spit-logo.png',
    chapter: 'Chapter I: Roots',
    quote: 'Four years of late-night labs that quietly shaped everything that followed.',
    skills: ['Java', 'Python', 'Data Structures', 'DBMS', 'Software Design'],
    bullets: [
      'Graduated with a B.Tech in Electronics & Telecommunication Engineering.',
      'Built a strong foundation in systems, algorithms, and software design.',
    ],
    story: 'It’s one thing to study a subject; it’s another to find your actual calling. While my degree was in Electronics & Telecommunication, I couldn’t quite see myself working in core electronics long-term.\n\nThe real turning point came when I started exploring beyond my major. I dove into Data Structures and Database Management, and an intensive bootcamp gave me hands-on experience with Web Dev, Data Analytics, and Machine Learning.\n\nThe IICDC 2019 hackathon was the turning point: semi-finalists out of 800+ teams, presenting an affordable non-invasive flow meter to Texas Instruments and the Dept. of Science & Technology, Govt. of India. That was the moment I realised I liked solving real problems more than textbook ones.\n\nOverall, SPIT taught me the discipline of building things properly — not just making them work, but understanding why they work.',
    photos: [
      { src: '/assets/images/journey/spit/graduation.jpg', caption: 'Graduation day at SPIT — the 4 years that quietly shaped everything.' },
      { src: '/assets/images/journey/spit/iicdc.png', caption: 'IICDC 2019 — Semi-finalists out of 800+ teams, presenting to Texas Instruments and the Dept. of Science & Technology, Govt. of India.' },
    ],
    transitionType: 'road',
  },
  {
    id: 'ltimindtree',
    label: 'LTIMindtree',
    org: 'LTIMindtree',
    role: 'Software Engineer',
    dateRange: 'Jan 2021 – Jun 2023',
    type: 'work',
    coordinates: [72.89386, 19.12544],
    location: 'Powai, Mumbai, India',
    logo: '/assets/images/ltimindtree-logo-blue.png',
    chapter: 'Chapter II: First Steps',
    quote: 'My first taste of real systems — where theory finally met production traffic.',
    skills: ['SAP', 'SQL', 'ABAP', 'Stakeholder Management'],
    bullets: [
      'Landed my first job as a Software Engineer, but not the kind I imagined.',
      'Worked extensively with SAP ABAP, quickly adapting to enterprise software development.',
      'Took ownership of SAP Release Management for a major client\'s North America and EMEA regions, implementing a structured framework that reduced release incidents by 84%.'
    ],
    story: 'Landing my first Software Engineer role felt like the ultimate dream realized — until I was placed in the SAP practice working entirely with ABAP. It was a complete departure from the tech stack I had anticipated, but I leaned into the challenge.\n\nI leveraged my foundational programming knowledge to rapidly decode how massive enterprise systems operated. Within a few months, I took ownership of SAP Release Management for a major client\'s North America and EMEA regions, implementing a structured framework that slashed release incidents by 84%.\n\nWhile I excelled in the role and gained invaluable insight into global project operations, I knew I didn\'t want my impact to be confined to a single, niche technology. I wanted to deeply understand software systems at an architectural level without boundaries.\n\nThat hunger for broader, unconstrained engineering was the exact push I needed to take a leap and pursue my Masters degree in the United States.',
    photos: [
      { src: '/assets/images/journey/ltimindtree/work.jpg', caption: 'Powai, Mumbai — where I first stepped into the world of enterprise software engineering.' },
    ],
    transitionType: 'road',
  },
  {
    id: 'tamu-ms',
    label: 'Texas A&M',
    org: 'Texas A&M University',
    role: 'MS in Management Information Systems',
    dateRange: 'Aug 2023 – May 2025',
    type: 'education',
    coordinates: [-96.3509327959807, 30.610918712268887],
    location: 'College Station, TX',
    logo: '/assets/images/tamu-logo.png',
    chapter: 'Chapter III: The Leap',
    quote: "I didn't cross twelve time zones to repeat what I already knew.",
    skills: ['Data Engineering', 'Machine Learning', 'Cloud Architecture', 'Analytics'],
    bullets: [
      'Pursued graduate studies at Texas A&M — a 14,000 km flight from home.',
      'Focused on data systems, AI applications, and the intersection of tech and management.',
    ],
    story: 'I crossed twelve time zones for this — 14,000 km from home, into a world I\'d only hear about. Leaving behind the comfort and safety net of Mumbai for a Masters degree in Texas was the biggest risk I\’ve ever taken.\n\nI didn\’t have all the answers, but I knew my calling wasn\'t in the IT services industry — I wanted to unbox complex systems and build truly impactful software. College Station became my proving ground, both for learning to navigate life entirely on my own and for rebuilding my technical foundation.\n\nSitting in lectures covering Databases, Agile Development, and Data Mining, I constantly had those "this is exactly why I came here" moments. Beyond the rigorous coursework, I was relentlessly tinkering — keeping a close eye on the rapidly evolving AI landscape and building small projects to understand the mechanics behind the hype, early experimentation that would ultimately shape my entire career trajectory.\n\nIt was a defining period of intense growth, late-night coding, and — thanks to my roommates — discovering a serious passion for Formula 1.',
    photos: [
      { src: '/assets/images/journey/tamu-ms/kyle-field.jpg', caption: 'Kyle Field, Texas A&M — College Station in all its Aggie glory.' },
      { src: '/assets/images/journey/tamu-ms/campus1.jpg', caption: 'Memorial Student Center and Simpson Drill Field, Texas A&M.' },
      { src: '/assets/images/journey/tamu-ms/graduation.jpg', caption: 'Graduation day — the 14,000 km journey paid off.' },
      { src: '/assets/images/journey/tamu-ms/sunset.jpg', caption: 'Texas sunsets hit different.' },
      { src: '/assets/images/journey/tamu-ms/rb18-2.jpg', caption: 'A very good day — next to the Red Bull RB18, Max\'s 2022 championship car.' },
    ],
    transitionType: 'flight',
  },
  {
    id: 'tamu-intern',
    label: 'Internship',
    org: 'Texas A&M (Remote)',
    role: 'Data Engineer Intern (Volunteer)',
    dateRange: 'Aug 2025 – Feb 2026',
    type: 'work',
    coordinates: [-121.9285478998405, 37.363915880380404],
    location: 'San Jose, CA (Remote)',
    // logo: '/assets/images/tamu-logo.png',
    chapter: 'Chapter III: The Leap',
    quote: 'The valley taught me that the best engineers are still the ones asking why.',
    skills: ['Python', 'SQL', 'AWS', 'Google ADK', 'AI Agents'],
    bullets: [
      'Volunteered as a data engineer intern while navigating the challenging post-graduation job market.',
      'The biggest toll was balancing the volunteer work with the uncertainty of the job market and the personal effort required to stay motivated and productive.',
    ],
    story: 'Graduating into the brutal 2025 job market - a landscape defined by mass layoffs, AI disruption, and relentless immigration hurdles for international students was a harsh reality check. Without a full-time role lined up, I flew out to San Jose to experience Silicon Valley.\n\nThe density of ambition in that place is unlike anything I\'d encountered before — everyone is building something, and the bar for \'good enough\' is permanently higher here. To keep my skills sharp and meet that standard, I secured a volunteer role under one of my professors at Texas A&M.\n\nMy days became a relentless, dual-track grind of academic research, certifications, hackathons, and complex side projects. It was also during this period that I built my own multi-agent AI system for a Google Hackathon - a project that would eventually become a defining talking point in my interviews.\n\nBut a hustle like that takes a toll. Amidst the uncertain days, sleepless nights, and the daily sting of 9 AM rejection emails, I had to learn how to manage myself to keep my hope alive. I started taking long walks, exploring the Bay Area, and making intentional time to clear my mind.\n\nIt was a grueling season, but it taught me how to sustain my own momentum, protect my mental bandwidth, and never lose faith in my abilities.',
    photos: [
      { src: '/assets/images/journey/tamu-intern/sv-sunset.jpg', caption: 'Silicon Valley sunset — the one that made the flight worth it.' },
      { src: '/assets/images/journey/tamu-intern/christmas-in-sjc.jpg', caption: 'Christmas in San Jose — experiencing the holiday season away from home.' },
    ],
    transitionType: 'flight',
  },
  {
    id: 'hcltech',
    label: 'HCLTech',
    org: 'HCLTech',
    role: 'AI Engineer, Agentic AI',
    dateRange: '2026 – Present',
    type: 'work',
    coordinates: [-122.14091255737284, 47.63891007775006],
    location: 'Redmond, WA',
    logo: '/assets/images/HCLT-logo.png',
    chapter: 'Chapter IV: Now',
    quote: "I'm not building tools anymore — I'm building agents that think, plan, and act. That line is blurring fast, and I'm close to where I want to be.",
    skills: ['RAG', 'Multi-Agent AI Systems', 'Azure OpenAI', 'Claude Code'],
    bullets: [
      'Based in Redmond, Washington — the Pacific Northwest.',
      'Building large-scale enterprise AI solutions with a focus on agentic systems.',
    ],
    story: 'Redmond, WA - where the mountains meet the rain and the rain meets the coffee. The Pacific Northwest has a way of making you feel small in the best possible way.\n\nProfessionally, landing the Agentic AI Engineer role felt like a hard-fought victory. Stationed right in the backyard of tech giants like Microsoft, I finally found myself working with the exact cutting-edge stack I had been chasing. My day-to-day involves architecting advanced multi-agent AI systems, but what excites me just as much is the exposure to the strategic side of the business — making critical decisions about what to build, when to pivot, and how to position these solutions for the market.\n\nWhile I’m proud of the enterprise systems I’m architecting today, my long-term ambition is scale. I want to sit at the heart of a product team, translating complex AI agents into intuitive, consumer-facing applications. The journey so far has been about mastering the technology; the next frontier is using it to build core products that directly shape the user\'s everyday life.',
    photos: [
      { src: '/assets/images/journey/hcltech/pike-place.jpg', caption: 'Pike Place Market, Seattle — the Pacific Northwest welcomed me right.' },
      { src: '/assets/images/journey/hcltech/sea-waterfront.jpg', caption: 'Seattle Waterfront — under the cloudy sky.' },
    ],
    transitionType: 'flight',
  },

  // ── Personal memory pins (visible in free explore mode) ───────────────────
  {
    id: 'wankhede',
    label: 'Wankhede Stadium',
    type: 'personal',
    coordinates: [72.8252, 18.9389],
    location: 'Wankhede Stadium, Mumbai',
    emoji: '🏏',
    story: 'My first time watching cricket in a stadium — and it happened to be Sachin Tendulkar. Wankhede holds 33,000 people and every single one of them was there for one man. I understood that this was something you don\'t forget. That\'s still true.',
    photos: [
      { src: '/assets/images/journey/personal/wankhede.mp4', caption: 'Wankhede Stadium — the day cricket became something I understood differently.' },
    ],
  },
  {
    id: 'mahalaxmi',
    label: 'First Martin Garrix Concert',
    type: 'personal',
    coordinates: [72.8201, 18.9845],
    location: 'Mahalaxmi Racecourse, Mumbai',
    emoji: '🎧',
    story: 'My first Martin Garrix concert — at Mahalaxmi Racecourse. Before this night, EDM was something I listened to through headphones. After it, it was something I felt in my chest.\n\nThe drop hit different at 130 dB with 15,000 people who all felt exactly the same thing at exactly the same moment.',
    photos: [
      { src: '/assets/images/journey/personal/martin-garrix.mp4', caption: 'Martin Garrix at Mahalaxmi. The night EDM went from headphones to everything.' },
    ],
  },
  {
    id: 'marine-drive',
    label: 'India wins the World Cup',
    type: 'personal',
    coordinates: [72.8234, 18.9336],
    location: 'Marine Drive, Mumbai',
    emoji: '🏆',
    story: 'June 29, 2024. India wins the T20 World Cup. I was on Marine Drive with 10,000 other people for the victory parade — the kind of crowd that turns a street into a memory. There\'s a video of this, and it still doesn\'t capture what it actually felt like to be standing in it.',
    photos: [
      { src: '/assets/images/journey/personal/marine-drive-t20.mov', caption: 'Marine Drive victory parade — India wins the 2024 T20 World Cup.' },
    ],
  },
  {
    id: 'sf-golden-gate',
    label: 'San Francisco',
    type: 'personal',
    coordinates: [-122.4784, 37.8197],
    location: 'Golden Gate Bridge, San Francisco, CA',
    emoji: '🌉',
    story: 'San Francisco was a day trip from San Jose. The fog, the bridge, the cold in June that nobody warns you about, the hills that make you question every transport decision you\'ve made.\n\nSometimes the best things aren\'t on the itinerary. This was one of those days.',
    photos: [
      { src: '/assets/images/journey/personal/golden-gate.jpg', caption: 'Golden Gate at dusk. SF taught me that the best things are rarely on the plan.' },
      { src: '/assets/images/journey/personal/sf-skyline.jpg', caption: 'The San Francisco skyline — the view that made the detour worth it.' },
    ],
  },
  {
    id: 'netherlands',
    label: 'The Netherlands',
    type: 'personal',
    coordinates: [4.9003, 52.3676],
    location: 'Amsterdam, The Netherlands',
    emoji: '🌷',
    story: 'Haven\'t been here yet — but the connection runs deep. More world-class EDM artists come from the Netherlands than anywhere else on earth: Hardwell, Martin Garrix, Armin van Buuren, Tiësto, Afrojack.\n\nThe country that gave the world the best music also gave it the best driver. Max Verstappen is Dutch. Enough said. This is also very much on the list.',
    photos: [
      { src: '/assets/images/journey/personal/amsterdam.jpg', caption: 'Amsterdam — EDM capital of the world and home of the GOAT.' },
    ],
  },
  {
    id: 'northern-lights',
    label: 'Northern Lights',
    type: 'personal',
    coordinates: [-11.6076, 60.8594],
    location: 'Somewhere over the Arctic Circle',
    emoji: '🌌',
    story: 'I captured Northern Lights from my flight back to India. Seeing the Northern Lights was a dream come true.\n\nThe sky danced with colors in a way that felt almost magical. It was a reminder of how vast and beautiful our world is.',
    photos: [
      { src: '/assets/images/journey/personal/northern-lights.jpg', caption: 'Northern Lights — a dream come true.' },
    ],
  },
  {
    id: 'rialto-beach',
    label: 'Rialto Beach',
    type: 'personal',
    coordinates: [-124.648361, 47.939667],
    location: 'Rialto Beach, Olympic National Park, WA',
    emoji: '🌊',
    story: 'Driftwood the size of buildings, sea stacks disappearing into fog, and the Pacific hitting the coast like it means it. Rialto Beach felt like the edge of the world — in the best way.',
    photos: [
      { src: '/assets/images/journey/personal/rialto-beach.MOV', caption: 'Rialto Beach — the edge of the world, Olympic Peninsula.' },
    ],
  },
  {
    id: 'hurricane-ridge',
    label: 'Hurricane Ridge',
    type: 'personal',
    coordinates: [-123.487417, 47.983694],
    location: 'Hurricane Ridge, Olympic National Park, WA',
    emoji: '🏔️',
    story: 'Snow-capped peaks in the middle of summer and a view that stretches across the entire Olympic range. Hurricane Ridge is proof that Washington hides mountains as good as anywhere in the world.',
    photos: [
      { src: '/assets/images/journey/personal/hurricane-ridge.jpg', caption: 'Hurricane Ridge — the Olympic Mountains on a clear day.' },
    ],
  },
  {
    id: 'crater-lake',
    label: 'Crater Lake',
    type: 'personal',
    coordinates: [-122.14675, 42.912111],
    location: 'Crater Lake National Park, OR',
    emoji: '🌋',
    story: 'The bluest water I\'ve ever seen — deeper and more saturated than any photo can capture. Crater Lake is a volcano that collapsed into itself and spent centuries filling with rain and snowmelt. Standing at the rim, it barely looks real.',
    photos: [
      { src: '/assets/images/journey/personal/crater-lake.MOV', caption: 'Crater Lake — a collapsed volcano filled with the bluest water on earth.' },
    ],
  },


  // ── Wishlist pins (visible in free explore mode) ──────────────────────────
  {
    id: 'banff',
    label: 'Banff National Park',
    type: 'wishlist',
    coordinates: [-115.9281, 51.4968],
    location: 'Banff, Alberta, Canada',
    note: 'The Rockies meet turquoise lakes. First Canadian stop on the list.',
  },
  {
    id: 'yellowstone',
    label: 'Yellowstone',
    type: 'wishlist',
    coordinates: [-110.5885, 44.4280],
    location: 'Yellowstone National Park, WY',
    note: 'Geysers, bison, and the raw power of the earth. A mandatory pilgrimage.',
  },
  {
    id: 'grand-canyon',
    label: 'Grand Canyon',
    type: 'wishlist',
    coordinates: [-112.1401, 36.0544],
    location: 'Grand Canyon, AZ',
    note: "Scale you can't comprehend until you're standing at the edge.",
  },
  {
    id: 'nyc',
    label: 'New York City',
    type: 'wishlist',
    coordinates: [-74.0060, 40.7128],
    location: 'New York City, NY',
    note: 'The city that never sleeps. Need to see it at least once.',
  },
  {
    id: 'las-vegas',
    label: 'Las Vegas',
    type: 'wishlist',
    coordinates: [-115.1398, 36.1699],
    location: 'Las Vegas, NV',
    note: 'EDM, F1 (Las Vegas Grand Prix), and the desert. Three very good reasons.',
  },
  {
    id: 'miami',
    label: 'Miami',
    type: 'wishlist',
    coordinates: [-80.1918, 25.7617],
    location: 'Miami, FL',
    note: 'Ultra Music Festival. The F1 Miami Grand Prix. The beach. The music.',
  },
  {
    id: 'colorado',
    label: 'Colorado',
    type: 'wishlist',
    coordinates: [-104.9903, 39.7392],
    location: 'Denver, Colorado',
    note: 'Mountains, skiing, and probably the best weekend drive in the US.',
  },
  {
    id: 'dubai',
    label: 'Dubai',
    type: 'wishlist',
    coordinates: [55.2708, 25.2048],
    location: 'Dubai, UAE',
    note: 'Where ambition becomes architecture. The scale of it is something else.',
  },
  {
    id: 'zurich',
    label: 'Zurich',
    type: 'wishlist',
    coordinates: [8.5417, 47.3769],
    location: 'Zurich, Switzerland',
    note: 'Precision, alpine air, and some of the best city infrastructure in Europe.',
  },
  {
    id: 'iceland',
    label: 'Vatnajökull',
    type: 'wishlist',
    coordinates: [-16.9798, 64.4115],
    location: 'Vatnajökull National Park, Iceland',
    note: 'Glaciers, northern lights, and landscapes that look like another planet.',
  },
  {
    id: 'tomorrowland',
    label: 'Tomorrowland',
    type: 'wishlist',
    coordinates: [4.3741, 51.0914],
    location: 'Boom, Belgium',
    note: 'The festival. The pilgrimage. Non-negotiable for anyone who loves electronic music.',
  },
  {
    id: 'cota',
    label: 'Circuit of the Americas',
    type: 'wishlist',
    coordinates: [-97.6352, 30.1328],
    location: 'Austin, TX',
    note: 'F1 in Austin — the closest Grand Prix to where I studied. Still need to go.',
  },

  // ── India wishlist ────────────────────────────────────────────────────────
  {
    id: 'leh-ladakh',
    label: 'Leh, Ladakh',
    type: 'wishlist',
    coordinates: [77.5771, 34.1526],
    location: 'Leh, Ladakh, India',
    note: 'The Himalayas at their most extreme — altitude, silence, and landscapes that make you feel genuinely small.',
  },
  {
    id: 'sikkim',
    label: 'Sikkim',
    type: 'wishlist',
    coordinates: [88.5122, 27.5330],
    location: 'Gangtok, Sikkim, India',
    note: 'Monasteries, mountains, and the kind of quiet you can\'t find in a city. The northeast is a different India entirely.',
  },
  {
    id: 'goa',
    label: 'Goa',
    type: 'wishlist',
    coordinates: [73.8278, 15.2993],
    location: 'Panaji, Goa, India',
    note: 'The trip that has been planned about 11 times and cancelled 11 times. Never made it out of the group chat. One day.',
  },
  {
    id: 'alappuzha',
    label: 'Alappuzha (Alleppey)',
    type: 'wishlist',
    coordinates: [76.3388, 9.4981],
    location: 'Alappuzha, Kerala, India',
    note: 'Backwaters, houseboats, and the kind of slow travel that feels like the exact opposite of every city I\'ve lived in.',
  },
  {
    id: 'udaipur',
    label: 'Udaipur',
    type: 'wishlist',
    coordinates: [73.6967, 24.5854],
    location: 'Udaipur, Rajasthan, India',
    note: 'The City of Lakes — Rajasthan\'s most cinematic city. The kind that makes you understand why they keep shooting films here.',
  },

  // ── Asia & Pacific wishlist ───────────────────────────────────────────────
  {
    id: 'singapore',
    label: 'Singapore',
    type: 'wishlist',
    coordinates: [103.8198, 1.3521],
    location: 'Singapore',
    note: 'Efficiency that puts everywhere else to shame, and a food scene that punches impossibly above its city-state size.',
  },
  {
    id: 'tokyo',
    label: 'Tokyo',
    type: 'wishlist',
    coordinates: [139.6917, 35.6895],
    location: 'Tokyo, Japan',
    note: 'A city that invented the future and still has the best ramen. Shibuya crossing at midnight is non-negotiable.',
  },
  {
    id: 'vietnam',
    label: 'Vietnam',
    type: 'wishlist',
    coordinates: [107.1839, 10.7769],
    location: 'Ho Chi Minh City, Vietnam',
    note: 'Phở at 6am, a coastline that doesn\'t look real, and the organised chaos of a country that moves at its own speed.',
  },
  {
    id: 'maldives',
    label: 'Maldives',
    type: 'wishlist',
    coordinates: [73.5093, 4.1755],
    location: 'North Malé Atoll, Maldives',
    note: 'The overwater bungalow is mandatory at some point. Hard to justify other than — it\'s the Maldives.',
  },
  {
    id: 'bangkok',
    label: 'Bangkok',
    type: 'wishlist',
    coordinates: [100.5018, 13.7563],
    location: 'Bangkok, Thailand',
    note: 'Street food that\'s better than most restaurants, temples between skyscrapers, and the controlled chaos of Khao San Road.',
  },
  {
    id: 'seoul',
    label: 'Seoul',
    type: 'wishlist',
    coordinates: [126.9780, 37.5665],
    location: 'Seoul, South Korea',
    note: 'Han River at night, incredible food infrastructure, and a city that moves faster than it should.',
  },
  {
    id: 'melbourne',
    label: 'Melbourne',
    type: 'wishlist',
    coordinates: [144.9631, -37.8136],
    location: 'Melbourne, Australia',
    note: 'Australia\'s most liveable city, and the F1 Australian Grand Prix opens every season here. The stars aligned.',
  },
  {
    id: 'hawaii',
    label: 'Hawaii',
    type: 'wishlist',
    coordinates: [-157.8583, 21.3069],
    location: 'Honolulu, Hawaii, USA',
    note: 'Volcanic coastline, zero cell service, and the most isolated archipelago on earth. A very specific kind of reset.',
  },
  {
    id: 'mauritius',
    label: 'Mauritius',
    type: 'wishlist',
    coordinates: [57.5522, -20.3484],
    location: 'Port Louis, Mauritius',
    note: 'Indian Ocean island — Creole food, lagoons, and the kind of blue water that doesn\'t look real in photos.',
  },

  // ── Europe wishlist ───────────────────────────────────────────────────────
  {
    id: 'berlin',
    label: 'Berlin',
    type: 'wishlist',
    coordinates: [13.4050, 52.5200],
    location: 'Berlin, Germany',
    note: 'Techno capital of the world. Berghain, the Wall, and a city that rebuilt itself into something genuinely electric.',
  },
  {
    id: 'tromso',
    label: 'Tromsø',
    type: 'wishlist',
    coordinates: [18.9553, 69.6492],
    location: 'Tromsø, Norway',
    note: 'The best place on earth to chase Northern Lights properly — not from an airplane window.',
  },
  {
    id: 'monaco',
    label: 'Monaco',
    type: 'wishlist',
    coordinates: [7.4246, 43.7384],
    location: 'Monaco, Monaco',
    note: 'The Grand Prix first, the city second. Everything in Monaco is designed to be seen from the right angle at speed.',
  },
  {
    id: 'bruges',
    label: 'Bruges',
    type: 'wishlist',
    coordinates: [3.2247, 51.2093],
    location: 'Bruges, Belgium',
    note: 'Medieval canals and a 5-minute train from Tomorrowland. Combining both in one trip is the only correct plan.',
  },
  {
    id: 'london',
    label: 'London',
    type: 'wishlist',
    coordinates: [-0.1276, 51.5074],
    location: 'London, UK',
    note: 'Wembley, Camden Market, and the fact that every EDM artist eventually plays here. The city is on the list.',
  },
];
