module.exports = [
  {
    id: 'home',
    label: 'Home',
    org: 'Borivali, Mumbai',
    role: 'Where it all began',
    dateRange: 'Origins',
    type: 'home',
    coordinates: [72.8573123399746, 19.229218251390936],
    location: 'Borivali, Mumbai, India',
    logo: null,
    chapter: 'Chapter I: Roots',
    quote: 'Every journey starts with the street you grew up on.',
    skills: [],
    bullets: [
      'Grew up in the northern suburbs of Mumbai.',
      'The city of hustle, monsoons, and vada pav — where curiosity about computers first sparked.'
    ],
    photos: [],
    transitionType: null,
  },
  {
    id: 'spit',
    label: 'SPIT',
    org: 'Sardar Patel Institute of Technology',
    role: 'B.Tech in Electronics & Telecommunication Engineering',
    dateRange: 'Aug 2017 – May 2021',
    type: 'education',
    coordinates: [72.83611859144854, 19.123210075271743],
    location: 'Andheri, Mumbai, India',
    logo: '/assets/images/spit-logo.png',
    chapter: 'Chapter I: Roots',
    quote: 'Four years of late-night labs that quietly shaped everything that followed.',
    skills: ['Java', 'Python', 'Data Structures', 'DBMS', 'Software Design'],
    bullets: [
      'Graduated with a B.Tech in Electronics & Telecommunication Engineering.',
      'Built a strong foundation in systems, algorithms, and software design.',
    ],
    photos: [],
    transitionType: 'road',
  },
  {
    id: 'ltimindtree',
    label: 'LTIMindtree',
    org: 'LTIMindtree',
    role: 'Software Engineer',
    dateRange: 'Jan 2021 – Jun 2023',
    type: 'work',
    coordinates: [72.89386, 19.12544],
    location: 'Powai, Mumbai, India',
    logo: '/assets/images/ltimindtree-logo-blue.png',
    chapter: 'Chapter II: First Steps',
    quote: 'My first taste of real systems — where theory finally met production traffic.',
    skills: ['Python', 'SQL', 'ETL', 'Azure', 'Spark', 'Data Pipelines'],
    bullets: [
      'Built and maintained large-scale data pipelines processing millions of records.',
      'Led migration of legacy ETL workflows to cloud-native Azure infrastructure.',
    ],
    photos: [],
    transitionType: 'road',
  },
  {
    id: 'tamu-ms',
    label: 'Texas A&M',
    org: 'Texas A&M University',
    role: 'MS in Management Information Systems',
    dateRange: 'Aug 2023 – May 2025',
    type: 'education',
    coordinates: [-96.3509327959807, 30.610918712268887],
    location: 'College Station, TX',
    logo: '/assets/images/tamu-logo.png',
    chapter: 'Chapter III: The Leap',
    quote: "I didn't cross twelve time zones to repeat what I already knew.",
    skills: ['Data Engineering', 'Machine Learning', 'Cloud Architecture', 'Analytics'],
    bullets: [
      'Pursued graduate studies at Texas A&M — a 14,000 km flight from home.',
      'Focused on data systems, AI applications, and the intersection of tech and management.',
      'Served as Teaching Assistant for database and analytics courses.',
    ],
    photos: [],
    transitionType: 'flight',
  },
  {
    id: 'tamu-intern',
    label: 'Internship',
    org: 'Texas A&M (Remote)',
    role: 'Data Engineer Intern',
    dateRange: 'Aug 2025 – Feb 2026',
    type: 'work',
    coordinates: [-121.9285478998405, 37.363915880380404],
    location: 'San Jose, CA (Remote)',
    logo: '/assets/images/tamu-logo.png',
    chapter: 'Chapter III: The Leap',
    quote: 'The valley taught me that the best engineers are still the ones asking why.',
    skills: ['Python', 'dbt', 'Snowflake', 'Airflow', 'SQL'],
    bullets: [
      'Remote internship based out of San Jose, California.',
      'Designed and deployed data transformation pipelines using dbt and Snowflake.',
    ],
    photos: [],
    transitionType: 'flight',
  },
  {
    id: 'hcltech',
    label: 'HCLTech',
    org: 'HCLTech',
    role: 'AI Engineer, Agentic AI',
    dateRange: '2026 – Present',
    type: 'work',
    coordinates: [-122.14091255737284, 47.63891007775006],
    location: 'Redmond, WA',
    logo: '/assets/images/HCLT-logo.png',
    chapter: 'Chapter IV: Now',
    quote: "I'm not building tools anymore — I'm building agents that think, plan, and act. That line is blurring fast, and I'm exactly where I want to be.",
    skills: ['RAG', 'LLM', 'Microsoft AI Stack', 'Azure AI', 'Agentic Systems'],
    bullets: [
      'Based in Redmond, Washington — the Pacific Northwest.',
      'Building large-scale enterprise AI solutions with a focus on agentic systems.',
    ],
    photos: [],
    transitionType: 'flight',
  },
];
